export const fetchProducts = async () => {
	const seedProducts = [
		{
			id: 1,
			collection_: "Autumn-Winter",
			title: "Stylish Double Bed",
			color: "Brown",
			category: "Bed",
			img: "/assets/images/bed5.jpg",
			price: 590,
			feature: false,
			rating: 4.5,
			review: 204,
		},
		{
			id: 2,
			collection_: "Autumn-Winter",
			title: "Double Bed Frame- Oak",
			color: "Beige",
			category: "Bed",
			img: "/assets/images/bed3.jpg",
			price: 550,
			feature: false,
			rating: 5,
			review: 344,
		},
		{
			id: 3,
			collection_: "Autumn-Winter",
			title: "3 Seater Leather Sofa",
			color: "Brown",
			category: "Sofa",
			img: "/assets/images/sofa2.jpg",
			price: 480,
			feature: false,
			rating: 4.5,
			review: 765,
		},
		{
			id: 4,
			collection_: "Spring-Summer",
			title: "WoodLand 3 Seater Sofa",
			color: "Lavender",
			category: "Sofa",
			img: "/assets/images/sofa6.jpg",
			price: 499,
			feature: false,
			rating: 5,
			review: 34,
		},
		{
			id: 5,
			collection_: "Spring-Summer",
			title: "Woodland Double Bed Frame",
			color: "Beige",
			category: "Bed",
			img: "/assets/images/bed1.jpg",
			price: 189,
			feature: false,
			rating: 4.5,
			review: 98,
		},
		{
			id: 6,
			collection_: "Autumn-Winter",
			title: "White & Black Double Bed",
			color: "Black",
			category: "Bed",
			img: "/assets/images/bed2.jpg",
			price: 299,
			feature: false,
			rating: 5,
			review: 564,
		},
		{
			id: 7,
			collection_: "Spring-Summer",
			title: "WoodLand 2 Seater Fabric Sofa",
			color: "Blue",
			category: "Sofa",
			img: "/assets/images/sofa1.jpg",
			price: 399,
			feature: true,
			rating: 5,
			review: 87,
		},
		{
			id: 8,
			collection_: "Autumn-Winter",
			title: "Kingsize Black Bed",
			color: "Black",
			category: "Bed",
			img: "/assets/images/bed4.jpg",
			price: 590,
			feature: false,
			rating: 4.5,
			review: 467,
		},
		{
			id: 9,
			collection_: "Spring-Summer",
			title: "WoodLand Fabric ArmChair",
			color: "Pink",
			category: "Chair",
			img: "/assets/images/chair6.jpg",
			price: 79,
			feature: true,
			rating: 5,
			review: 12,
		},
		{
			id: 10,
			collection_: "Spring-Summer",
			title: "Modern Double Bed",
			color: "Brown",
			category: "Bed",
			img: "/assets/images/bed6.jpg",
			price: 390,
			feature: false,
			rating: 4.5,
			review: 43,
		},
		{
			id: 11,
			collection_: "Spring-Summer",
			title: "Royal Bed Kingsize",
			color: "White",
			category: "Bed",
			img: "/assets/images/bed7.jpg",
			price: 590,
			feature: false,
			rating: 5,
			review: 98,
		},
		{
			id: 12,
			collection_: "Spring-Summer",
			title: "White Armchair",
			color: "White",
			category: "Chair",
			img: "/assets/images/chair1.jpg",
			price: 150,
			feature: false,
			rating: 5,
			review: 47,
		},
		{
			id: 13,
			collection_: "Spring-Summer",
			title: "Cocktail Fabric Chair",
			color: "Yellow",
			category: "Chair",
			img: "/assets/images/chair2.jpg",
			price: 250,
			feature: false,
			rating: 5,
			review: 370,
		},
		{
			id: 14,
			collection_: "Autumn-Winter",
			title: "WoodLand Velvet Chair",
			color: "Brown",
			category: "Chair",
			img: "/assets/images/chair3.jpg",
			price: 180,
			feature: false,
			rating: 4.5,
			review: 381,
		},
		{
			id: 15,
			collection_: "Autumn-Winter",
			title: "Old Fashioned Chocktail Chair",
			color: "Yellow",
			category: "Chair",
			img: "/assets/images/chair4.jpg",
			price: 120,
			feature: false,
			rating: 4.5,
			review: 417,
		},
		{
			id: 16,
			collection_: "Autumn-Winter",
			title: "Modern Dinning Chair",
			color: "Brown",
			category: "Chair",
			img: "/assets/images/chair5.jpg",
			price: 280,
			feature: false,
			rating: 5,
			review: 932,
		},
		{
			id: 17,
			collection_: "Autumn-Winter",
			title: "WoodLand Velvet Armchair-White",
			color: "White",
			category: "Chair",
			img: "/assets/images/chair.jpg",
			price: 169,
			feature: true,
			rating: 4.5,
			review: 65,
		},
		{
			id: 18,
			collection_: "Spring-Summer",
			title: "WoodLand White Shade",
			color: "Grey",
			category: "Lamp",
			img: "/assets/images/lamp.jpg",
			price: 59,
			feature: false,
			rating: 5,
			review: 51,
		},
		{
			id: 19,
			collection_: "Autumn-Winter",
			title: "WoodLand 2 Seater Velvet Sofa",
			color: "Grey",
			category: "Sofa",
			img: "/assets/images/sofa4.jpg",
			price: 519,
			feature: false,
			rating: 4.5,
			review: 8,
		},
		{
			id: 20,
			collection_: "Spring-Summer",
			title: "White Fabric Sofa",
			color: "White",
			category: "Sofa",
			img: "/assets/images/sofa5.jpg",
			price: 389,
			feature: false,
			rating: 4.5,
			review: 89,
		},
		{
			id: 21,
			collection_: "Autumn-Winter",
			title: "WoodLand 3 Seater Velvet Sofa",
			color: "Green",
			category: "Sofa",
			img: "/assets/images/sofa3.jpg",
			price: 499,
			feature: true,
			rating: 5,
			review: 63,
		},
		{
			id: 22,
			collection_: "Spring-Summer",
			title: "WoodLand Velvet Sofa- Beige",
			color: "Beige",
			category: "Sofa",
			img: "/assets/images/sofa7.jpg",
			price: 499,
			feature: false,
			rating: 5,
			review: 754,
		},
		{
			id: 23,
			collection_: "Autumn-Winter",
			title: "Fabric Sofa with Table",
			color: "Brown",
			category: "Sofa",
			img: "/assets/images/table1.jpg",
			price: 399,
			feature: false,
			rating: 5,
			review: 987,
		},
		{
			id: 24,
			collection_: "Autumn-Winter",
			title: "Simple White Coffe Table",
			color: "White",
			category: "Table",
			img: "/assets/images/table2.jpg",
			price: 199,
			feature: false,
			rating: 4.5,
			review: 353,
		},
		{
			id: 25,
			collection_: "Autumn-Winter",
			title: "Green Sylish Sofa with Coffe Table",
			color: "Green",
			category: "Sofa",
			img: "/assets/images/table3.jpg",
			price: 390,
			feature: false,
			rating: 5,
			review: 156,
		},
		{
			id: 26,
			collection_: "Autumn-Winter",
			title: "Fabric Sofa with Coffe Table",
			color: "Black",
			category: "Sofa",
			img: "/assets/images/table4.jpg",
			price: 390,
			feature: false,
			rating: 4.5,
			review: 378,
		},
		{
			id: 27,
			collection_: "Spring-Summer",
			title: "Modern Fabric Sofa with Coffe Table",
			color: "Grey",
			category: "Sofa",
			img: "/assets/images/table5.jpg",
			price: 490,
			feature: false,
			rating: 5,
			review: 258,
		},
		{
			id: 28,
			collection_: "Autumn-Winter",
			title: "WoodLand Fabric Sofa with Coffe Table",
			color: "Grey",
			category: "Sofa",
			img: "/assets/images/table6.jpg",
			price: 290,
			feature: false,
			rating: 4.5,
			review: 73,
		},
		{
			id: 29,
			collection_: "Autumn-Winter",
			title: "New WoodLand Furniture",
			color: "Beige",
			category: "Sofa",
			img: "/assets/images/g.jpg",
			price: 590,
			feature: false,
			rating: 5,
			review: 92,
		},
		{
			id: 30,
			collection_: "Spring-Summer",
			title: "Leather Sofa with Table",
			color: "Brown",
			category: "Sofa",
			img: "/assets/images/g1.jpg",
			price: 419,
			feature: false,
			rating: 4.5,
			review: 74,
		},
		{
			id: 31,
			collection_: "Autumn-Winter",
			title: "Grey Sofa with Table",
			color: "Grey",
			category: "Sofa",
			img: "/assets/images/g2.jpg",
			price: 490,
			feature: false,
			rating: 5,
			review: 26,
		},
		{
			id: 32,
			collection_: "Spring-Summer",
			title: "Modern Sofa with Table",
			color: "White",
			category: "Sofa",
			img: "/assets/images/g3.jpg",
			price: 590,
			feature: false,
			rating: 5,
			review: 29,
		},
		{
			id: 33,
			collection_: "Spring-Summer",
			title: "New and Modern Furniture",
			color: "Grey",
			category: "Sofa",
			img: "/assets/images/g4.jpg",
			price: 690,
			feature: false,
			rating: 5,
			review: 45,
		},
		{
			id: 34,
			collection_: "Autumn-Winter",
			title: "WoodLand Table Lamp",
			color: "White",
			category: "Lamp",
			img: "/assets/images/bed3.jpg",
			price: 28,
			feature: false,
			rating: 4.5,
			review: 34,
		},
		{
			id: 35,
			collection_: "Spring-Summer",
			title: "WoodLand Table Lamp",
			color: "Grey",
			category: "Lamp",
			img: "/assets/images/bed7.jpg",
			price: 50,
			feature: false,
			rating: 5,
			review: 85,
		},
		{
			id: 36,
			collection_: "Spring-Summer",
			title: "WoodLand White Table",
			color: "White",
			category: "Table",
			img: "/assets/images/sofa5.jpg",
			price: 189,
			feature: false,
			rating: 4.5,
			review: 954,
		},
		{
			id: 37,
			collection_: "Spring-Summer",
			title: "WoodLand Table lamp",
			color: "Lavender",
			category: "Lamp",
			img: "/assets/images/sofa6.jpg",
			price: 99,
			feature: false,
			rating: 5,
			review: 637,
		},
		{
			id: 38,
			collection_: "Spring-Summer",
			title: "WoodLand Coffe Table-Beige",
			color: "Beige",
			category: "Table",
			img: "/assets/images/sofa7.jpg",
			price: 150,
			feature: false,
			rating: 5,
			review: 267,
		},
		{
			id: 39,
			collection_: "Autumn-Winter",
			title: "WoodLand Coffe Table",
			color: "Brown",
			category: "Table",
			img: "/assets/images/table1.jpg",
			price: 200,
			feature: false,
			rating: 4.5,
			review: 472,
		},
		{
			id: 40,
			collection_: "Autumn-Winter",
			title: "WoodLand Coffe Table",
			color: "Brown",
			category: "Table",
			img: "/assets/images/table3.jpg",
			price: 199,
			feature: false,
			rating: 5,
			review: 782,
		},
		{
			id: 41,
			collection_: "Autumn-Winter",
			title: "Coffe Table",
			color: "Brown",
			category: "Table",
			img: "/assets/images/table4.jpg",
			price: 129,
			feature: false,
			rating: 5,
			review: 97,
		},
		{
			id: 42,
			collection_: "Spring-Summer",
			title: "WoodLand Coffe Table",
			color: "White",
			category: "Table",
			img: "/assets/images/table5.jpg",
			price: 129,
			feature: false,
			rating: 4.5,
			review: 765,
		},
	];
	return seedProducts;
};
